-- ARREGLA VALOR POR DEFECTO EN CAMPOS 101,102 Y 103 DEL FORMATO 101
UPDATE FDInformacion SET valor= '21 - RIESGO NO EVALUADO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('101','102','103') AND  CAST(VALOR AS VARCHAR(MAX))='0 - NO'
SELECT * FROM FDInformacion  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('101','102','103') AND  CAST(VALOR AS VARCHAR(MAX))='0 - NO'

-- ARREGLA VALOR POR DEFECTO EN CAMPO 107 DEL FORMATO 101
UPDATE FDInformacion SET valor= '21 - RIESGO NO EVALUADO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('107') AND  CAST(VALOR AS VARCHAR(MAX))='3 - RIESGO NO EVALUADO'
UPDATE FDInformacion SET valor= '3 - NO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('107') AND  CAST(VALOR AS VARCHAR(MAX))='0 - NO'

SELECT * FROM FDInformacion  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('107')

-- ARREGLA VALOR POR DEFECTO EN CAMPO 109 DEL FORMATO 101
UPDATE FDInformacion SET valor= '21 - RIESGO NO EVALUADO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('109') AND  CAST(VALOR AS VARCHAR(MAX))='4 - RIESGO NO EVALUADO'
UPDATE FDInformacion SET valor= '3 - NO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('109') AND  CAST(VALOR AS VARCHAR(MAX))='0 - NO'
UPDATE FDInformacion SET valor= '0 - NO APLICA'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('109') AND  CAST(VALOR AS VARCHAR(MAX))='3 - NO APLICA'


SELECT * FROM FDInformacion  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('109')

-- ARREGLA VALOR POR DEFECTO EN CAMPO 111,113,116 DEL FORMATO 101
UPDATE FDInformacion SET valor= '21 - RIESGO NO EVALUADO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('111','113','116') AND  CAST(VALOR AS VARCHAR(MAX))='3 - RIESGO NO EVALUADO'
UPDATE FDInformacion SET valor= '21 - RIESGO NO EVALUADO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('111','113','116') AND  CAST(VALOR AS VARCHAR(MAX))='4 - RIESGO NO EVALUADO'
UPDATE FDInformacion SET valor= '3 - NO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('111','113','116') AND  CAST(VALOR AS VARCHAR(MAX))='0 - NO'
UPDATE FDInformacion SET valor= '21 - RIESGO NO EVALUADO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('111','113','116') AND  CAST(VALOR AS VARCHAR(MAX))='2 - NO APLICA'

SELECT * FROM FDInformacion  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('111','113','116')

-- ARREGLA VALOR POR DEFECTO EN CAMPO 114 DEL FORMATO 101
UPDATE FDInformacion SET valor= '21 - RIESGO NO EVALUADO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('114') AND  CAST(VALOR AS VARCHAR(MAX))='7 - RIESGO NO EVALUADO'
UPDATE FDInformacion SET valor= '7 - NO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('114') AND  CAST(VALOR AS VARCHAR(MAX))='0 - NO'

SELECT * FROM FDInformacion  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('114')

-- ARREGLA VALOR POR DEFECTO EN CAMPO 115 DEL FORMATO 101
UPDATE FDInformacion SET valor= '21 - RIESGO NO EVALUADO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('115') AND  CAST(VALOR AS VARCHAR(MAX))='3 - RIESGO NO EVALUADO'
UPDATE FDInformacion SET valor= '0 - NO APLICA'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('115') AND  CAST(VALOR AS VARCHAR(MAX))='2 - NO APLICA'
UPDATE FDInformacion SET valor= '2 - NO'  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('115') AND  CAST(VALOR AS VARCHAR(MAX))='0 - NO'

SELECT * FROM FDInformacion  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('115')


