-- ARREGLA VALOR POR DEFECTO EN CAMPO 107 DEL FORMATO 101
UPDATE FDOpciones SET VALOR =  REPLACE(REPLACE (CAST(Valor as varchar(max)),'3 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','3 - NO')   WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('107') 
SELECT *, REPLACE(REPLACE (CAST(Valor as varchar(max)),'3 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','3 - NO') FROM FDOpciones  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('107') 

-- ARREGLA VALOR POR DEFECTO EN CAMPO 109 DEL FORMATO 101
UPDATE FDOpciones SET VALOR = REPLACE(REPLACE(REPLACE (CAST(Valor as varchar(max)),'4 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','3 - NO'),'3 - NO APLICA','0 - NO APLICA')  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('109') 
SELECT *, REPLACE(REPLACE(REPLACE (CAST(Valor as varchar(max)),'4 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','3 - NO'),'3 - NO APLICA','0 - NO APLICA') FROM FDOpciones  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('109') 


-- ARREGLA VALOR POR DEFECTO EN CAMPOS 111,113,116 DEL FORMATO 101
DELete FDOpciones  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('111','113','116') AND valor = '2 - NO APLICA'
UPDATE FDOpciones SET VALOR = REPLACE(REPLACE (CAST(Valor as varchar(max)),'3 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','2 - NO')  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('111','113','116')  
UPDATE FDOpciones SET VALOR = REPLACE(REPLACE (CAST(Valor as varchar(max)),'3 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0- NO','2 - NO')  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('111','113','116')  

SELECT *, REPLACE(REPLACE (CAST(Valor as varchar(max)),'3 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','2 - NO')  FROM FDOpciones  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('111','113','116') 


 -- ARREGLA VALOR POR DEFECTO EN CAMPOS 114 DEL FORMATO 101
UPDATE FDOpciones SET VALOR = REPLACE(REPLACE (CAST(Valor as varchar(max)),'7 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','7 - NO') WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('114')  
SELECT *, REPLACE(REPLACE (CAST(Valor as varchar(max)),'7 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','7 - NO')
 FROM FDOpciones  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('114') 

 
 -- ARREGLA VALOR POR DEFECTO EN CAMPOS 115 DEL FORMATO 101
UPDATE FDOpciones SET VALOR = REPLACE(REPLACE(REPLACE (CAST(Valor as varchar(max)),'3 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','2 - NO'),'2 - NO APLICA','0 - NO APLICA')  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('115')  
SELECT *, REPLACE(REPLACE(REPLACE (CAST(Valor as varchar(max)),'3 - RIESGO NO EVALUADO','21 - RIESGO NO EVALUADO' ),'0 - NO','2 - NO'),'2 - NO APLICA','0 - NO APLICA')  
 FROM FDOpciones  WHERE CODIGO_FORMATO='101' AND CODIGO_SECCION='102' AND CODIGO_CAMPO IN ('115') 

