program Consultorios;

uses
  Forms,
  MAIN in 'MAIN.PAS' {MainForm},
  about in '..\..\..\ColossoLittle\Fuentes\Comunes\about.pas' {AboutBox},
  CapturaBasicaSelect in '..\..\..\ColossoLittle\Fuentes\Comunes\CapturaBasicaSelect.pas' {CapturaBasicaS},
  CHILDWIN in '..\..\..\ColossoLittle\Fuentes\Comunes\CHILDWIN.PAS' {MDIChild},
  Reporteador in '..\..\..\ColossoLittle\Fuentes\Comunes\Reporteador.pas' {GenReport},
  UDataModule1 in '..\..\..\ColossoLittle\Fuentes\Comunes\UDataModule1.pas' {DataModule1: TDataModule},
  FInfReg in '..\..\..\ColossoLittle\Fuentes\Comunes\FInfReg.pas' {FormInfReg},
  ImportaPlanos in '..\..\..\ColossoLittle\Fuentes\Comunes\ImportaPlanos.pas' {ImportPlano},
  FSolicitud in '..\Control de Cargos\FSolicitud.pas' {FSolicitaCargo},
  frmGrupos in '..\..\..\ColossoLittle\Fuentes\Inventarios\frmGrupos.pas' {Grupos},
  frmservicios in '..\Admisiones\frmservicios.pas' {Servicios},
  FrmCalculoTarifa in '..\Control de Cargos\FrmCalculoTarifa.pas' {FCalculoTarifa},
  SAPAcientesShort in '..\Admisiones\SAPAcientesShort.pas' {FrmIngresoPacientesShort},
  AnulaAdmision in '..\Admisiones\AnulaAdmision.pas' {FAnulaAdmi},
  FHojaAdmision in '..\Admisiones\FHojaAdmision.pas' {FrmHojaAdmision},
  FHojaAdmisionSmall2 in '..\Admisiones\FHojaAdmisionSmall2.pas' {FrmHojaAdmisionSmall2},
  ModuloAdmision in '..\Admisiones\ModuloAdmision.pas' {DatamoduloAdmision: TDataModule},
  UingresosAdmisiones in '..\Admisiones\UingresosAdmisiones.pas' {frmAdminsiones},
  SAEgresos in '..\Admisiones\SAEgresos.pas' {frmEgresos},
  ImportaPlanosPaci in '..\Admisiones\ImportaPlanosPaci.pas' {ImportPlanoAdmi},
  UAdmisiones in '..\Admisiones\UAdmisiones.pas' {frmAdmisiones},
  UAdmisiones2 in 'UAdmisiones2.pas' {frmProcAdmision},
  FCajaFormato in '..\..\..\ColossoLittle\Fuentes\Control de Caja\FCajaFormato.pas' {CajaFormato},
  FImpBoleta in '..\Control de Cargos\FImpBoleta.pas' {ImpBoleta},
  ComplementoAdmi in '..\Facturacion\ComplementoAdmi.pas' {FCompAdm},
  fKardex in '..\..\..\ColossoLittle\Fuentes\Inventarios\fKardex.pas' {Kardex},
  FCargos in '..\Control de Cargos\FCargos.pas' {FCapturaCargo},
  FImpriTransacc in '..\..\..\ColossoLittle\Fuentes\Inventarios\FImpriTransacc.pas' {FormImpInventa},
  UIngresoCajaMultiple in '..\Control de Caja\UIngresoCajaMultiple.pas' {IngresosFacturaM},
  ActLote in '..\Inventarios\ActLote.pas' {ActualizacionInvent},
  FAsignaGrupo in '..\Facturacion\FAsignaGrupo.pas' {FrmAsignaGrupo},
  UnitBusquedas in '..\Admisiones\UnitBusquedas.pas' {FrmBusquedas},
  UnitCitasDiarias in '..\Admisiones\UnitCitasDiarias.pas' {FrmCitasDiarias},
  FFacturaporPaciente in '..\Facturacion\FFacturaporPaciente.pas' {FacturaDirectaxPac},
  CapturaBasica2 in '..\..\..\ColossoLittle\Fuentes\Comunes\CapturaBasica2.pas' {CapturaB2},
  FHojaAdmisionSmallAut in '..\Admisiones\FHojaAdmisionSmallAut.pas' {FrmHojaAdmisionSmallAut},
  FImprimeFormato2 in '..\Admisiones\FImprimeFormato2.pas' {FImprimeFmto2},
  RecalculaSaldo in '..\..\..\ColossoLittle\Fuentes\Inventarios\RecalculaSaldo.pas' {RegeneraSaldos},
  frmAnulacion in '..\..\..\ColossoLittle\Fuentes\Inventarios\frmAnulacion.pas' {FAnula},
  FActivarInactivar in '..\..\..\ColossoLittle\Fuentes\Comunes\FActivarInactivar.pas' {FrmAI},
  FImpresionFactura in '..\Facturacion\FImpresionFactura.pas' {FImprimeFactura},
  FProdxArea in '..\Facturacion\FProdxArea.pas' {FrmProdxArea},
  FrmAsignaHomo in '..\Facturacion\FrmAsignaHomo.pas' {frmAsignaHomologa},
  FCrearConvenio in '..\Facturacion\FCrearConvenio.pas' {FormCreaConvenios},
  clibmp in '..\CompoderWindows2010\Cliente\clibmp.pas' {FormBmp},
  Cliente in '..\CompoderWindows2010\Cliente\Cliente.pas' {FormComprobador},
  clitext in '..\CompoderWindows2010\Cliente\clitext.pas' {FormText},
  Mensaje in '..\CompoderWindows2010\Cliente\Mensaje.pas' {FormMensaje},
  Lista_Tablas2 in '..\..\..\ColossoLittle\Fuentes\Comunes\Lista_Tablas2.pas' {FListadoTablasCol},
  FrameListaTabla2 in '..\..\..\ColossoLittle\Fuentes\Comunes\FrameListaTabla2.pas' {ListaCol: TFrame},
  FrameMenuOpcion in '..\..\..\ColossoLittle\Fuentes\Comunes\FrameMenuOpcion.pas' {FrameMnOp: TFrame},
  ImprimeFormato in '..\..\..\ColossoLittle\Fuentes\Comunes\ImprimeFormato.pas' {ImpFormato},
  SACreaEmpresas in '..\..\..\ColossoLittle\Fuentes\Comunes\SACreaEmpresas.pas' {FrmIngresoEmpresas},
  CapturaBasica in '..\..\..\ColossoLittle\Fuentes\Comunes\CapturaBasica.pas' {CapturaB},
  frmproductos in '..\..\..\ColossoLittle\Fuentes\Inventarios\frmproductos.pas' {Productos},
  FAsignaCapitulo in '..\Facturacion\FAsignaCapitulo.pas' {FrmAsignaCapitulo},
  CapturaBasica3 in '..\..\..\ColossoLittle\Fuentes\Comunes\CapturaBasica3.pas' {CapturaB3},
  SAPAcientes2 in '..\Admisiones\SAPAcientes2.pas' {FrmIngresoPacientes},
  GemaPaint in '..\..\..\ColossoLittle\Fuentes\Comunes\GemaPaint.pas' {FrmPaint},
  WebCam in '..\..\..\ColossoLittle\Fuentes\Comunes\WebCam.pas',
  WebCamForm in '..\..\..\ColossoLittle\Fuentes\Comunes\WebCamForm.pas' {WebCamF},
  FImpresionFacturaSmall in '..\Facturacion\FImpresionFacturaSmall.pas' {FImprimeFacturaSmall},
  FImpresionFacturaSmall2 in '..\Facturacion\FImpresionFacturaSmall2.pas' {FImprimeFacturaSmall2},
  FHojaAdmisionSmall in '..\Admisiones\FHojaAdmisionSmall.pas' {FrmHojaAdmisionSmall},
  FDescargos in '..\Control de Cargos\FDescargos.pas' {Descargos},
  CajaEmbell in '..\Embell\CajaEmbell.pas' {FCajaEmbell},
  FAgendaMedica in '..\Citasmedicas\FAgendaMedica.pas' {FAgenda},
  ProgramacionAutomatica in '..\Citasmedicas\ProgramacionAutomatica.pas' {ProgAuto},
  FBMsgWait in '..\..\..\ColossoLittle\Fuentes\Comunes\Librerias\FBMsgWait.pas' {PrateincoMsgWait},
  Libreria_Prateinco in '..\..\..\ColossoLittle\Fuentes\Comunes\Librerias\Libreria_Prateinco.pas',
  Libreria_PrateincoForm in '..\..\..\ColossoLittle\Fuentes\Comunes\Librerias\Libreria_PrateincoForm.pas',
  UParametrosAdmi in '..\Admisiones\UParametrosAdmi.pas' {ParametrosAdm},
  DelphiTwain in '..\..\..\Componentes\Digitalizacion\delphitwain\DelphiTwain.pas',
  DelphiTwainUtils in '..\..\..\Componentes\Digitalizacion\delphitwain\DelphiTwainUtils.pas',
  Twain in '..\..\..\Componentes\Digitalizacion\delphitwain\Twain.pas',
  SEIngreso in '..\..\..\ColossoLittle\Fuentes\Menu\SEIngreso.pas' {FIngreso},
  FDetPaquete in '..\Control de Cargos\FDetPaquete.pas' {FrmDetPaquete},
  FCreaTerceros in '..\Contabilidad\FCreaTerceros.pas' {FrmCrearTerceros},
  FElimSolicitud in '..\Facturacion\FElimSolicitud.pas' {EliminaCargo},
  Vcl.Themes,
  Vcl.Styles,
  VerificaHuella in '..\Sistema Medico\VerificaHuella.pas' {FVHuella},
  FImpSolicitud in '..\Control de Cargos\FImpSolicitud.pas' {ImpSolicitud};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TDataModule1, DataModule1);
  Application.CreateForm(TDatamoduloAdmision, DatamoduloAdmision);
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
